language: generic

services:
  - docker

cache:
  directories:
  - docker_images
before_install:
- docker load -i docker_images/images.tar || true
before_cache:
- docker save -o docker_images/images.tar $(docker images -a -q)

script:
  - docker build -t shepherdjerred/spigot:latest .

deploy:
  - provider: script
    script: >-
      echo "$DOCKER_PASSWORD" | docker login -u shepherdjered --password-stdin
      && docker push
    on:
      branch: master
  - provider: script
    script: >-
      echo "$GITHUB_PASSWORD" | docker login docker.pkg.github.com -u shepherdjerred --password-stdin
      && docker tag shepherdjerred/spigot:latest docker.pkg.github.com/shepherdjerred-minecraft/spigot-docker/shepherdjerred/spigot:latest
      && docker push docker.pkg.github.com/shepherdjerred-minecraft/spigot-docker/IMAGE_NAME:VERSION
      && docker push
    on:
      branch: master
