language: generic

services:
  - docker

script:
  - docker build -t shepherdjerred/spigot:latest .

deploy:
  - provider: script
    script: >-
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      && docker push
    on:
      branch: master
  - provider: script
    script: >-
      echo "$GITHUB_PASSWORD" | docker login docker.pkg.github.com -u shepherdjerred --password-stdin
      && docker tag shepherdjerred/spigot:latest docker.pkg.github.com/shepherdjerred-minecraft/spigot-docker/shepherdjerred/spigot:latest
      && docker push docker.pkg.github.com/shepherdjerred-minecraft/spigot-docker/IMAGE_NAME:VERSION
      && docker push
    on:
      branch: master
